### ISSUE TITLE
Bug: Crash on clicking dice

### ISSUE THREAD

**Issue by Justus188** [Justus188/ESA-2021-Team10#7]
Gets following error message when clicking dice:
Warning: Error in which: object 'CELLRED' not found
Suspect that it is from updateBoardState() in restaurant+movement.R, since CELLRED is only defined in Shiny.R

**Comment by max-koh** [comment]
created a pull request by removing global variables in restaurant + movement.

**Comment by Justus188** [comment]
Now its:
Warning: Error in updateBoardState: argument "gridsize" is missing, with no default
from line 354 D:
To discuss later during team meeting

**Comment by Justus188** [comment]
Resolved
